-- 3goods: coverage organisations (DECISIONS.md D-070). Run once in the Supabase SQL Editor.
-- 23 fictional organisations spread over provinces in proportion to the map's real community-facility distribution,
-- with their login users and needs; 10 of them sit on real OSM facility coordinates so their map pins show as matched (D-073). Also adds organisations.lat/lng and
-- the facility_interests table. Idempotent (re-running updates the same rows). One transaction.
-- Requires supabase/migration-provinces.sql to have been run (province slugs, unit "items", one-need-per-category index).
-- Generated by scripts/build-coverage-sql.mjs from src/data/coverage.js: edit that, not this.

begin;

-- Map pins <-> organisations (DECISIONS.md D-073). (a) An optional exact position on organisations, so a facility pin can be matched
-- to a registered organisation by distance. (b) A small insert-only table for the "this facility hasn't joined yet" interest form.
alter table organisations add column if not exists lat double precision;
alter table organisations add column if not exists lng double precision;

create table if not exists facility_interests (
  id uuid primary key default gen_random_uuid(),
  osm_type text,
  osm_id text,
  facility_name text not null,
  facility_lat double precision,
  facility_lon double precision,
  contact_name text not null,
  contact text not null,
  locale text,
  created_at timestamptz not null default now()
);
alter table facility_interests enable row level security;
drop policy if exists "public insert only" on facility_interests;
create policy "public insert only" on facility_interests for insert to anon, authenticated with check (true);
-- (no select policy on purpose: the public key can write an interest but cannot read anyone's contact details back)

insert into organisations (id, name, name_vi, description, description_vi, city, lat, lng, verified, is_demo, past_received_item_ids) values
  ('dd7a5003-f92a-46f8-8de1-a862639e0aaf', 'Ba Ria-Vung Tau Neighbours Support Network', 'Mạng lưới Hàng xóm hỗ trợ Bà Rịa-Vũng Tàu', 'Neighbours in Ba Ria-Vung Tau pooling essentials for households in a bad month.', 'Hàng xóm ở Bà Rịa-Vũng Tàu chung tay chia sẻ nhu yếu phẩm cho các hộ gia đình gặp khó khăn.', 'ba-ria-vung-tau', null, null, true, true, '{}'),
  ('8c6d7d23-103e-4afd-b765-46686f8fd5b5', 'Ba Ria-Vung Tau Warm Meals Kitchen', 'Bếp ăn ấm áp Bà Rịa-Vũng Tàu', 'A volunteer kitchen serving hot meals and packing food parcels in Ba Ria-Vung Tau.', 'Bếp tình nguyện nấu bữa ăn nóng và đóng gói thực phẩm cho người dân Bà Rịa-Vũng Tàu.', 'ba-ria-vung-tau', 10.438, 107.22105, true, true, '{}'),
  ('1f5a6c98-a1bc-4002-9be4-64028fc00abe', 'Ba Ria-Vung Tau School Supplies Drive', 'Chương trình đồ dùng học tập Bà Rịa-Vũng Tàu', 'Getting books, bags and stationery to schoolchildren in Ba Ria-Vung Tau.', 'Đưa sách vở, cặp và dụng cụ học tập đến học sinh ở Bà Rịa-Vũng Tàu.', 'ba-ria-vung-tau', null, null, true, true, '{}'),
  ('456df6c7-0175-497c-a967-489ceca4de20', 'Bac Ninh Youth Volunteers', 'Thanh niên tình nguyện Bắc Ninh', 'Student volunteers collecting and sorting donations across Bac Ninh.', 'Sinh viên tình nguyện thu gom và phân loại đồ quyên góp trên khắp Bắc Ninh.', 'bac-ninh', 21.19318, 106.08492, false, true, '{}'),
  ('1a648247-62c8-4630-a9da-114edefc3f11', 'Binh Dinh Flood Response Team', 'Đội ứng phó lũ Bình Định', 'Pre-positioning blankets, clean water and dry food for flood season in Binh Dinh.', 'Chuẩn bị chăn, nước sạch và thực phẩm khô cho mùa lũ ở Bình Định.', 'binh-dinh', null, null, true, true, '{}'),
  ('fa779f42-6342-4c74-8f7f-002bcc7937b5', 'Can Tho Elders Care Group', 'Nhóm chăm sóc người cao tuổi Cần Thơ', 'Supporting older people living alone in Can Tho with food, hygiene items and company.', 'Hỗ trợ người cao tuổi sống một mình ở Cần Thơ bằng thực phẩm, vật dụng vệ sinh và sự đồng hành.', 'can-tho', 10.03524, 105.77349, true, true, '{}'),
  ('ff95d789-79a0-475b-b4e5-53758ef94aaf', 'Helping Hands Dong Nai', 'Bàn tay giúp đỡ Đồng Nai', 'A small local group matching families in Dong Nai with the household goods they need.', 'Nhóm địa phương kết nối các gia đình ở Đồng Nai với đồ dùng gia đình họ đang cần.', 'dong-nai', 10.96149, 106.87273, true, true, '{}'),
  ('b9efc1f0-7716-4162-8343-2c1c4a91da9a', 'Hanoi Family Relief Circle', 'Vòng tròn cứu trợ gia đình Hà Nội', 'Helping families in Hanoi recover after storms with food, clothing and bedding.', 'Giúp các gia đình ở Hà Nội phục hồi sau bão với thực phẩm, quần áo và chăn màn.', 'hanoi', null, null, false, true, '{}'),
  ('d99ce8ae-7135-41b5-a7f5-c8c509d06df8', 'Hanoi Health & Hygiene Aid', 'Hỗ trợ y tế và vệ sinh Hà Nội', 'Hygiene kits and basic supplies for families and clinics in Hanoi.', 'Bộ vật dụng vệ sinh và nhu yếu phẩm cơ bản cho các gia đình và trạm y tế ở Hà Nội.', 'hanoi', null, null, true, true, '{}'),
  ('612d3fb9-7228-47a9-82d8-25adb09c5c36', 'Hanoi Clothing Bank', 'Ngân hàng quần áo Hà Nội', 'Clean, usable clothing collected and handed on to people in Hanoi.', 'Quần áo sạch, còn dùng được được thu gom và trao lại cho người dân Hà Nội.', 'hanoi', 20.9826, 105.7788, true, true, '{}'),
  ('21238dee-34e2-42db-b063-62c2f62501cb', 'Hanoi Harvest Share', 'Chia sẻ mùa vàng Hà Nội', 'Rice and dry goods shared with farming households in Hanoi after a poor season.', 'Chia sẻ gạo và thực phẩm khô với các hộ nông dân ở Hà Nội sau mùa vụ kém.', 'hanoi', null, null, true, true, '{}'),
  ('b2d7ec25-eec5-4861-8228-fe4ea37f75c1', 'Hanoi Shelter Partners', 'Đối tác mái ấm Hà Nội', 'Blankets, mats and basics for people staying in temporary shelters in Hanoi.', 'Chăn, chiếu và đồ dùng thiết yếu cho người ở nơi trú tạm ở Hà Nội.', 'hanoi', 20.8072, 105.71436, false, true, '{}'),
  ('a0478549-ff0a-4bff-bc10-01d272cec5db', 'Hanoi Neighbours Support Network', 'Mạng lưới Hàng xóm hỗ trợ Hà Nội', 'Neighbours in Hanoi pooling essentials for households in a bad month.', 'Hàng xóm ở Hà Nội chung tay chia sẻ nhu yếu phẩm cho các hộ gia đình gặp khó khăn.', 'hanoi', null, null, true, true, '{}'),
  ('0abb73b4-11b2-4be2-972c-82169a5c9043', 'Hanoi Warm Meals Kitchen', 'Bếp ăn ấm áp Hà Nội', 'A volunteer kitchen serving hot meals and packing food parcels in Hanoi.', 'Bếp tình nguyện nấu bữa ăn nóng và đóng gói thực phẩm cho người dân Hà Nội.', 'hanoi', 21.01501, 105.74148, true, true, '{}'),
  ('aae3fd05-b35e-4bd5-9b00-65f828635a3d', 'Hanoi School Supplies Drive', 'Chương trình đồ dùng học tập Hà Nội', 'Getting books, bags and stationery to schoolchildren in Hanoi.', 'Đưa sách vở, cặp và dụng cụ học tập đến học sinh ở Hà Nội.', 'hanoi', null, null, true, true, '{}'),
  ('904ff7b6-c2a9-4000-802a-d39216b11538', 'Hai Phong Youth Volunteers', 'Thanh niên tình nguyện Hải Phòng', 'Student volunteers collecting and sorting donations across Hai Phong.', 'Sinh viên tình nguyện thu gom và phân loại đồ quyên góp trên khắp Hải Phòng.', 'hai-phong', null, null, false, true, '{}'),
  ('d0ad6eb5-3020-4c38-b026-48a576bab2f5', 'Ho Chi Minh City Flood Response Team', 'Đội ứng phó lũ Hồ Chí Minh', 'Pre-positioning blankets, clean water and dry food for flood season in Ho Chi Minh City.', 'Chuẩn bị chăn, nước sạch và thực phẩm khô cho mùa lũ ở Hồ Chí Minh.', 'ho-chi-minh-city', null, null, true, true, '{}'),
  ('1f457a59-6e77-4293-927d-65687fa991e0', 'Ho Chi Minh City Elders Care Group', 'Nhóm chăm sóc người cao tuổi Hồ Chí Minh', 'Supporting older people living alone in Ho Chi Minh City with food, hygiene items and company.', 'Hỗ trợ người cao tuổi sống một mình ở Hồ Chí Minh bằng thực phẩm, vật dụng vệ sinh và sự đồng hành.', 'ho-chi-minh-city', 10.79633, 106.71021, true, true, '{}'),
  ('d79e22e8-f97c-41e5-bacc-ceb142e0ce2a', 'Helping Hands Ho Chi Minh City', 'Bàn tay giúp đỡ Hồ Chí Minh', 'A small local group matching families in Ho Chi Minh City with the household goods they need.', 'Nhóm địa phương kết nối các gia đình ở Hồ Chí Minh với đồ dùng gia đình họ đang cần.', 'ho-chi-minh-city', 10.76648, 106.68866, true, true, '{}'),
  ('8f7a88f1-2648-40d3-b3fc-10be7d2dacdc', 'Nghe An Family Relief Circle', 'Vòng tròn cứu trợ gia đình Nghệ An', 'Helping families in Nghe An recover after storms with food, clothing and bedding.', 'Giúp các gia đình ở Nghệ An phục hồi sau bão với thực phẩm, quần áo và chăn màn.', 'nghe-an', null, null, false, true, '{}'),
  ('58101f34-8827-4f14-b9c5-a7c0314dabc4', 'Phu Tho Health & Hygiene Aid', 'Hỗ trợ y tế và vệ sinh Phú Thọ', 'Hygiene kits and basic supplies for families and clinics in Phu Tho.', 'Bộ vật dụng vệ sinh và nhu yếu phẩm cơ bản cho các gia đình và trạm y tế ở Phú Thọ.', 'phu-tho', null, null, true, true, '{}'),
  ('1ccb871f-06a8-4cdb-a295-ede55a393650', 'Thai Binh Clothing Bank', 'Ngân hàng quần áo Thái Bình', 'Clean, usable clothing collected and handed on to people in Thai Binh.', 'Quần áo sạch, còn dùng được được thu gom và trao lại cho người dân Thái Bình.', 'thai-binh', null, null, true, true, '{}'),
  ('4e45dc5b-7916-416e-897e-40b9809bf56a', 'Thanh Hoa Harvest Share', 'Chia sẻ mùa vàng Thanh Hóa', 'Rice and dry goods shared with farming households in Thanh Hoa after a poor season.', 'Chia sẻ gạo và thực phẩm khô với các hộ nông dân ở Thanh Hóa sau mùa vụ kém.', 'thanh-hoa', 19.74844, 105.86737, true, true, '{}')
on conflict (id) do update set name = excluded.name, name_vi = excluded.name_vi, description = excluded.description,
  description_vi = excluded.description_vi, city = excluded.city, lat = excluded.lat, lng = excluded.lng,
  verified = excluded.verified, is_demo = excluded.is_demo;

insert into users (id, name, role, org_id) values
  ('9797cbee-bb29-42a4-a546-aa4e742824e1', 'Ba Ria-Vung Tau Neighbours Support Network', 'organisation', 'dd7a5003-f92a-46f8-8de1-a862639e0aaf'),
  ('af225c63-2320-4863-93d9-745b41bd190d', 'Ba Ria-Vung Tau Warm Meals Kitchen', 'organisation', '8c6d7d23-103e-4afd-b765-46686f8fd5b5'),
  ('092b5ac7-0698-43f0-964f-59a164607b77', 'Ba Ria-Vung Tau School Supplies Drive', 'organisation', '1f5a6c98-a1bc-4002-9be4-64028fc00abe'),
  ('9dc69c85-b8a2-4d6d-b9b4-279d8f497d17', 'Bac Ninh Youth Volunteers', 'organisation', '456df6c7-0175-497c-a967-489ceca4de20'),
  ('98feaf24-f73a-4014-b9b7-84acda7b4ccc', 'Binh Dinh Flood Response Team', 'organisation', '1a648247-62c8-4630-a9da-114edefc3f11'),
  ('74e21a0e-4698-41b5-b12e-6007e70cf8d7', 'Can Tho Elders Care Group', 'organisation', 'fa779f42-6342-4c74-8f7f-002bcc7937b5'),
  ('40ddd273-c628-41a3-a3de-44722ceab8f6', 'Helping Hands Dong Nai', 'organisation', 'ff95d789-79a0-475b-b4e5-53758ef94aaf'),
  ('39c61662-f402-4d03-8dc0-355a8bced925', 'Hanoi Family Relief Circle', 'organisation', 'b9efc1f0-7716-4162-8343-2c1c4a91da9a'),
  ('ebfecf88-33bf-416b-abac-56e78f2c33b7', 'Hanoi Health & Hygiene Aid', 'organisation', 'd99ce8ae-7135-41b5-a7f5-c8c509d06df8'),
  ('3a9cfa9d-d386-48ac-8f37-f889bee3db5c', 'Hanoi Clothing Bank', 'organisation', '612d3fb9-7228-47a9-82d8-25adb09c5c36'),
  ('244bcebc-77bf-400e-999a-a01e92e31d86', 'Hanoi Harvest Share', 'organisation', '21238dee-34e2-42db-b063-62c2f62501cb'),
  ('4340c48b-7c61-4290-90b9-4fef50dfa46f', 'Hanoi Shelter Partners', 'organisation', 'b2d7ec25-eec5-4861-8228-fe4ea37f75c1'),
  ('aa4918ca-e70b-40b2-b15e-f93aaf77d258', 'Hanoi Neighbours Support Network', 'organisation', 'a0478549-ff0a-4bff-bc10-01d272cec5db'),
  ('aa84522b-4c6d-46db-b943-0a2de3c2a213', 'Hanoi Warm Meals Kitchen', 'organisation', '0abb73b4-11b2-4be2-972c-82169a5c9043'),
  ('8beccccf-2149-4208-b146-777f8df91d25', 'Hanoi School Supplies Drive', 'organisation', 'aae3fd05-b35e-4bd5-9b00-65f828635a3d'),
  ('7eb82e04-c1e3-4ded-8003-13ec2386424e', 'Hai Phong Youth Volunteers', 'organisation', '904ff7b6-c2a9-4000-802a-d39216b11538'),
  ('9daeef75-6de1-4bf2-9bd8-1bc778b5ab9d', 'Ho Chi Minh City Flood Response Team', 'organisation', 'd0ad6eb5-3020-4c38-b026-48a576bab2f5'),
  ('d8ac1fa3-1466-4bf3-bebe-cc3843fe54e7', 'Ho Chi Minh City Elders Care Group', 'organisation', '1f457a59-6e77-4293-927d-65687fa991e0'),
  ('650307dd-7792-415a-8b11-f8faf075c5ec', 'Helping Hands Ho Chi Minh City', 'organisation', 'd79e22e8-f97c-41e5-bacc-ceb142e0ce2a'),
  ('f2975cc3-6544-4da5-83e8-97b603686901', 'Nghe An Family Relief Circle', 'organisation', '8f7a88f1-2648-40d3-b3fc-10be7d2dacdc'),
  ('c1adbcb0-8cd2-41f6-98e3-c45188f1757c', 'Phu Tho Health & Hygiene Aid', 'organisation', '58101f34-8827-4f14-b9c5-a7c0314dabc4'),
  ('42c783ad-5893-4532-a7a2-a95df982e605', 'Thai Binh Clothing Bank', 'organisation', '1ccb871f-06a8-4cdb-a295-ede55a393650'),
  ('9f539156-7305-4000-936e-4a5fbc98b324', 'Thanh Hoa Harvest Share', 'organisation', '4e45dc5b-7916-416e-897e-40b9809bf56a')
on conflict (id) do update set name = excluded.name, role = excluded.role, org_id = excluded.org_id;

insert into needs (id, org_id, category_id, priority, quantity, unit, status, created_at) values
  ('cef91db6-79b4-4766-9d83-4f5690347ebc', 'dd7a5003-f92a-46f8-8de1-a862639e0aaf', (select id from categories where lower(name) = lower('Rice')), 'high', 30, 'items', 'open', '2026-09-21T02:10:00.000Z'),
  ('a8c7b771-f500-433e-9f24-f7ac1d90472b', 'dd7a5003-f92a-46f8-8de1-a862639e0aaf', (select id from categories where lower(name) = lower('Household Items')), 'medium', 50, 'items', 'open', '2026-09-21T02:10:00.000Z'),
  ('681f3223-668e-4a46-96a6-1deee8f5ed7c', '8c6d7d23-103e-4afd-b765-46686f8fd5b5', (select id from categories where lower(name) = lower('Rice')), 'high', 60, 'items', 'open', '2026-09-21T02:11:00.000Z'),
  ('b2381960-c9d4-4ef5-987a-0c5f3fa75407', '8c6d7d23-103e-4afd-b765-46686f8fd5b5', (select id from categories where lower(name) = lower('Non-Perishable Food')), 'medium', 80, 'items', 'open', '2026-09-21T02:11:00.000Z'),
  ('51ce86e5-c443-4c17-ac86-01cda359ca44', '1f5a6c98-a1bc-4002-9be4-64028fc00abe', (select id from categories where lower(name) = lower('Books')), 'high', 90, 'items', 'open', '2026-09-21T02:12:00.000Z'),
  ('d9e6192d-1831-46e6-9f92-75a62144f566', '1f5a6c98-a1bc-4002-9be4-64028fc00abe', (select id from categories where lower(name) = lower('Children Items')), 'medium', 110, 'items', 'open', '2026-09-21T02:12:00.000Z'),
  ('f2f1b85f-4234-4bd6-8328-eb42a89d2038', '456df6c7-0175-497c-a967-489ceca4de20', (select id from categories where lower(name) = lower('Clothes')), 'high', 120, 'items', 'open', '2026-09-21T02:13:00.000Z'),
  ('c9ed280c-8f22-4b39-949c-6f22ca7b1218', '456df6c7-0175-497c-a967-489ceca4de20', (select id from categories where lower(name) = lower('Hygiene Products')), 'medium', null, null, 'open', '2026-09-21T02:13:00.000Z'),
  ('7d2940a5-cd26-4105-9fa1-b1e69c5f099c', '456df6c7-0175-497c-a967-489ceca4de20', (select id from categories where lower(name) = lower('Miscellaneous')), 'medium', 160, 'items', 'open', '2026-09-21T02:13:00.000Z'),
  ('4282ad2f-cf6a-4a87-b500-71c768e4915c', '1a648247-62c8-4630-a9da-114edefc3f11', (select id from categories where lower(name) = lower('Household Items')), 'high', null, null, 'open', '2026-09-21T02:14:00.000Z'),
  ('3ae8cd11-7475-4124-b04e-e9f55c54d0cf', '1a648247-62c8-4630-a9da-114edefc3f11', (select id from categories where lower(name) = lower('Non-Perishable Food')), 'medium', 170, 'items', 'open', '2026-09-21T02:14:00.000Z'),
  ('906e0118-11ec-494f-b9cc-12201186c4eb', 'fa779f42-6342-4c74-8f7f-002bcc7937b5', (select id from categories where lower(name) = lower('Hygiene Products')), 'high', 180, 'items', 'open', '2026-09-21T02:15:00.000Z'),
  ('f5eaaa64-a475-445b-ac6e-3dc2bc46ea81', 'fa779f42-6342-4c74-8f7f-002bcc7937b5', (select id from categories where lower(name) = lower('Rice')), 'medium', 30, 'items', 'open', '2026-09-21T02:15:00.000Z'),
  ('6a2d2fb4-f88d-4db9-b738-c468be7e03a6', 'fa779f42-6342-4c74-8f7f-002bcc7937b5', (select id from categories where lower(name) = lower('Clothes')), 'medium', 50, 'items', 'open', '2026-09-21T02:15:00.000Z'),
  ('0d2aeb5e-0ddc-4fe3-b221-d6bd69f0b1d1', 'ff95d789-79a0-475b-b4e5-53758ef94aaf', (select id from categories where lower(name) = lower('Household Items')), 'high', 40, 'items', 'open', '2026-09-21T02:16:00.000Z'),
  ('fc3f2045-4339-4d7d-84b8-0ffc1cf33d7c', 'ff95d789-79a0-475b-b4e5-53758ef94aaf', (select id from categories where lower(name) = lower('Children Items')), 'medium', 60, 'items', 'open', '2026-09-21T02:16:00.000Z'),
  ('74d55e77-626f-438e-961c-9c5638d4f67d', 'b9efc1f0-7716-4162-8343-2c1c4a91da9a', (select id from categories where lower(name) = lower('Non-Perishable Food')), 'high', 70, 'items', 'open', '2026-09-21T02:17:00.000Z'),
  ('b09afd4d-dd96-4b36-80dc-2083b4cbe41d', 'b9efc1f0-7716-4162-8343-2c1c4a91da9a', (select id from categories where lower(name) = lower('Clothes')), 'medium', 90, 'items', 'open', '2026-09-21T02:17:00.000Z'),
  ('9f71cee4-be83-4674-8d14-ff9cf74f54b7', 'b9efc1f0-7716-4162-8343-2c1c4a91da9a', (select id from categories where lower(name) = lower('Household Items')), 'medium', null, null, 'open', '2026-09-21T02:17:00.000Z'),
  ('bea0255a-64af-4eb5-bed0-9c07166e5349', 'd99ce8ae-7135-41b5-a7f5-c8c509d06df8', (select id from categories where lower(name) = lower('Hygiene Products')), 'high', 100, 'items', 'open', '2026-09-21T02:18:00.000Z'),
  ('36cf7a9d-6342-4f46-af73-f2dc2487cff8', 'd99ce8ae-7135-41b5-a7f5-c8c509d06df8', (select id from categories where lower(name) = lower('Children Items')), 'medium', null, null, 'open', '2026-09-21T02:18:00.000Z'),
  ('fb5b51de-1ce6-471a-baa3-ac61609805a8', '612d3fb9-7228-47a9-82d8-25adb09c5c36', (select id from categories where lower(name) = lower('Clothes')), 'high', null, null, 'open', '2026-09-21T02:19:00.000Z'),
  ('8df6d7a0-01d6-4a7d-bc8c-b9a1b8f290db', '612d3fb9-7228-47a9-82d8-25adb09c5c36', (select id from categories where lower(name) = lower('Miscellaneous')), 'medium', 150, 'items', 'open', '2026-09-21T02:19:00.000Z'),
  ('dcc8c67c-1787-4896-821a-bb03b6dbcf5f', '21238dee-34e2-42db-b063-62c2f62501cb', (select id from categories where lower(name) = lower('Rice')), 'high', 160, 'items', 'open', '2026-09-21T02:20:00.000Z'),
  ('324db569-ed2f-468e-8e28-b8e4bc575175', '21238dee-34e2-42db-b063-62c2f62501cb', (select id from categories where lower(name) = lower('Non-Perishable Food')), 'medium', 180, 'items', 'open', '2026-09-21T02:20:00.000Z'),
  ('5b791547-5452-4eb8-8c6f-fb83dfd767ae', 'b2d7ec25-eec5-4861-8228-fe4ea37f75c1', (select id from categories where lower(name) = lower('Household Items')), 'high', 190, 'items', 'open', '2026-09-21T02:21:00.000Z'),
  ('3fb07c94-376a-480b-8fbe-304baae5c9a6', 'b2d7ec25-eec5-4861-8228-fe4ea37f75c1', (select id from categories where lower(name) = lower('Hygiene Products')), 'medium', 40, 'items', 'open', '2026-09-21T02:21:00.000Z'),
  ('64e17461-3fb7-46ed-ad79-7e26a5d46380', 'b2d7ec25-eec5-4861-8228-fe4ea37f75c1', (select id from categories where lower(name) = lower('Clothes')), 'medium', 60, 'items', 'open', '2026-09-21T02:21:00.000Z'),
  ('73634a97-0750-4065-89b7-ed071ec211b4', 'a0478549-ff0a-4bff-bc10-01d272cec5db', (select id from categories where lower(name) = lower('Rice')), 'high', 50, 'items', 'open', '2026-09-21T02:22:00.000Z'),
  ('0f4b03db-b7aa-4b90-9587-b57e4c4f9a46', 'a0478549-ff0a-4bff-bc10-01d272cec5db', (select id from categories where lower(name) = lower('Household Items')), 'medium', 70, 'items', 'open', '2026-09-21T02:22:00.000Z'),
  ('e0233a74-5661-4a1c-8865-1a8a81998bed', '0abb73b4-11b2-4be2-972c-82169a5c9043', (select id from categories where lower(name) = lower('Rice')), 'high', 80, 'items', 'open', '2026-09-21T02:23:00.000Z'),
  ('b8e2bbe6-3554-45c7-9a48-17b1281264e3', '0abb73b4-11b2-4be2-972c-82169a5c9043', (select id from categories where lower(name) = lower('Non-Perishable Food')), 'medium', null, null, 'open', '2026-09-21T02:23:00.000Z'),
  ('3b1b647c-c429-428a-a531-78985728836a', 'aae3fd05-b35e-4bd5-9b00-65f828635a3d', (select id from categories where lower(name) = lower('Books')), 'high', null, null, 'open', '2026-09-21T02:24:00.000Z'),
  ('79677dba-49ab-4ffd-8f75-a0012360efca', 'aae3fd05-b35e-4bd5-9b00-65f828635a3d', (select id from categories where lower(name) = lower('Children Items')), 'medium', 130, 'items', 'open', '2026-09-21T02:24:00.000Z'),
  ('a9d3e9bd-20f8-4ad2-9dbf-1524ce4ac795', '904ff7b6-c2a9-4000-802a-d39216b11538', (select id from categories where lower(name) = lower('Clothes')), 'high', 140, 'items', 'open', '2026-09-21T02:25:00.000Z'),
  ('6d7e97a2-89ac-4d99-9794-aa53252d6c9b', '904ff7b6-c2a9-4000-802a-d39216b11538', (select id from categories where lower(name) = lower('Hygiene Products')), 'medium', 160, 'items', 'open', '2026-09-21T02:25:00.000Z'),
  ('a381761c-210a-42ae-880b-27ebfcf71986', '904ff7b6-c2a9-4000-802a-d39216b11538', (select id from categories where lower(name) = lower('Miscellaneous')), 'medium', 180, 'items', 'open', '2026-09-21T02:25:00.000Z'),
  ('4d6989be-6625-4ded-b7b0-3bb41043fddf', 'd0ad6eb5-3020-4c38-b026-48a576bab2f5', (select id from categories where lower(name) = lower('Household Items')), 'high', 170, 'items', 'open', '2026-09-21T02:26:00.000Z'),
  ('9423d883-043b-4035-ae47-99436cb24575', 'd0ad6eb5-3020-4c38-b026-48a576bab2f5', (select id from categories where lower(name) = lower('Non-Perishable Food')), 'medium', 190, 'items', 'open', '2026-09-21T02:26:00.000Z'),
  ('cd4fdfbc-d52e-479c-9713-8a8a900fce3a', '1f457a59-6e77-4293-927d-65687fa991e0', (select id from categories where lower(name) = lower('Hygiene Products')), 'high', 30, 'items', 'open', '2026-09-21T02:27:00.000Z'),
  ('bf5f51ec-5e1e-48e7-8970-37f28e343265', '1f457a59-6e77-4293-927d-65687fa991e0', (select id from categories where lower(name) = lower('Rice')), 'medium', 50, 'items', 'open', '2026-09-21T02:27:00.000Z'),
  ('ab0587db-dc16-4205-bf0c-ae772ae07d81', '1f457a59-6e77-4293-927d-65687fa991e0', (select id from categories where lower(name) = lower('Clothes')), 'medium', null, null, 'open', '2026-09-21T02:27:00.000Z'),
  ('491ee15c-90af-4c63-b3a5-370a07d4488d', 'd79e22e8-f97c-41e5-bacc-ceb142e0ce2a', (select id from categories where lower(name) = lower('Household Items')), 'high', 60, 'items', 'open', '2026-09-21T02:28:00.000Z'),
  ('6837cc1b-cec6-4114-b9bd-5aa070d8e186', 'd79e22e8-f97c-41e5-bacc-ceb142e0ce2a', (select id from categories where lower(name) = lower('Children Items')), 'medium', null, null, 'open', '2026-09-21T02:28:00.000Z'),
  ('679054db-6fc3-4ae9-90cb-674f7d475426', '8f7a88f1-2648-40d3-b3fc-10be7d2dacdc', (select id from categories where lower(name) = lower('Non-Perishable Food')), 'high', null, null, 'open', '2026-09-21T02:29:00.000Z'),
  ('f2cb7799-1597-4cbf-bb17-544ae405ee6e', '8f7a88f1-2648-40d3-b3fc-10be7d2dacdc', (select id from categories where lower(name) = lower('Clothes')), 'medium', 110, 'items', 'open', '2026-09-21T02:29:00.000Z'),
  ('a26519e5-d7ac-4c95-baec-bb77136e991b', '8f7a88f1-2648-40d3-b3fc-10be7d2dacdc', (select id from categories where lower(name) = lower('Household Items')), 'medium', 130, 'items', 'open', '2026-09-21T02:29:00.000Z'),
  ('8e71a1d3-61bf-4fec-a6b7-ab09319ed6be', '58101f34-8827-4f14-b9c5-a7c0314dabc4', (select id from categories where lower(name) = lower('Hygiene Products')), 'high', 120, 'items', 'open', '2026-09-21T02:30:00.000Z'),
  ('497a0347-27d4-4b03-bd32-b831bb8b04ee', '58101f34-8827-4f14-b9c5-a7c0314dabc4', (select id from categories where lower(name) = lower('Children Items')), 'medium', 140, 'items', 'open', '2026-09-21T02:30:00.000Z'),
  ('a7b4d3b7-09d8-47d2-96d2-4503b3d70068', '1ccb871f-06a8-4cdb-a295-ede55a393650', (select id from categories where lower(name) = lower('Clothes')), 'high', 150, 'items', 'open', '2026-09-21T02:31:00.000Z'),
  ('30dc2aca-a3d1-4476-a994-ecbde97e6bac', '1ccb871f-06a8-4cdb-a295-ede55a393650', (select id from categories where lower(name) = lower('Miscellaneous')), 'medium', 170, 'items', 'open', '2026-09-21T02:31:00.000Z'),
  ('3b6ad921-fd78-42d2-92fe-07067cac5a87', '4e45dc5b-7916-416e-897e-40b9809bf56a', (select id from categories where lower(name) = lower('Rice')), 'high', 180, 'items', 'open', '2026-09-21T02:32:00.000Z'),
  ('5e3b6161-983f-4396-a020-8683c0a0d9bf', '4e45dc5b-7916-416e-897e-40b9809bf56a', (select id from categories where lower(name) = lower('Non-Perishable Food')), 'medium', 30, 'items', 'open', '2026-09-21T02:32:00.000Z')
on conflict (id) do update set org_id = excluded.org_id, category_id = excluded.category_id, priority = excluded.priority,
  quantity = excluded.quantity, unit = excluded.unit, status = excluded.status;

commit;

-- Check afterwards: organisations per province (expect 31 in total, Hanoi 9 first) and how many have coordinates (expect 10)
--   select city, count(*) from organisations group by city order by count(*) desc;
--   select count(*) from organisations where lat is not null;
